### ISSUE TITLE
barebones version of source_pkg

### ISSUE THREAD

**Issue by MichaelChirico** [jtilly/install_github#1]
i love the idea... it's always a pain to get `devtools` to install because of the litany of dependencies (considering I have to date exclusively used it for installing from GH)

suggested functionality:

add in a method similar in spirit but for [`devtools:::source_pkg`](https://github.com/hadley/devtools/blob/49eb27329c5a4d9dde3b67db953f8ec95879519a/R/decompress.r).

i [need this](http://stackoverflow.com/a/35631160/3576984) to install from GH to an offline machine.

Perhaps just source [the end](https://github.com/jtilly/install_github/blob/gh-pages/install_github.R#L107) separately?

**Comment by MichaelChirico** [comment]
nvm... not sure what `source_pkg` does actually. i was able to just use `install.packages` directly...

**Comment by jtilly** [comment]
Thanks, Mike! This is super interesting.
